#pragma once
#include <memory>
#include <map>
#include <string>
#include <vector>
#include <iostream>
#include <filesystem>
#include <SFML/Audio.hpp>
#include <SFML/Graphics.hpp>
#include <SFML/System.hpp>
#include <SFML/Graphics/RenderWindow.hpp>
#include "tileson.hpp"
#include "Trigonometry.h"
#include "VectorAlgebra2D.h"